CREATE TABLE users(
   user_id  SERIAL  PRIMARY KEY NOT NULL,
   name  VARCHAR(50) NOT NULL,
   email  VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   isactive  BOOLEAN DEFAULT false NOT NULL
);